name: Merge openroad branch into master branch
on:
  # This is just to disable the cron job
  push:
    tags: BOGUS_TAG
  #schedule:
  #  - cron: '* * * * *'
jobs:
  pullRequest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - name: Reset promotion branch
        run: |
          git fetch origin openroad:openroad
          git reset --hard openroad
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v2.8.1
        with:
          branch: staging
          base: master
          labels: automerge
          title: Merge branch 'staging' into 'master'
          body: |
            PR to update master branch (generated automatically by Github Actions)
