name: Update master branch
on:
  schedule:
    - cron: '* * * * *'
jobs:
  pullRequest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v2.8.1
        with:
          branch: openroad
          base: master
          labels: automerge
